#Dockerfile enter image description here A Dockerfile is a simple text file that contains the commands a user could call to assemble an image.
#Your Docker workflow should be to build a suitable Dockerfile for each image you wish to create, 
#then use compose to assemble the images using the build command.

FROM php:7.4-apache
MAINTAINER "naelson.g.saraiva@gmail.com"

#WORKDIR ./images-apache/app
#WORKDIR ./images-apache/config

#RUN rm -rf /usr/share/nginx/html/*
# copy ./app/* /usr/share/nginx/html/