#Dockerfile enter image description here A Dockerfile is a simple text file that contains the commands a user could call to assemble an image.
#Your Docker workflow should be to build a suitable Dockerfile for each image you wish to create, 
#then use compose to assemble the images using the build command.

FROM php:7.2-apache
#COPY src/ /var/www/html/

# sudo docker build -t phpseven .
# sudo docker run -dp 8090:80 phpseven
# sudo docker run -d --name phpruning phpseven